# ----------- Dev -------------------
version: "3.5"
services:

  rabbitmq-dev:
    image: rabbitmq:3.11
    container_name: rabbitmq-dev
    ports:
      - 5672:5672

  mailhog-dev:
    image: mailhog/mailhog:latest
    container_name: mailhog-dev
    ports:
      - 1025:1025 # smtp port
      - 8025:8025 # http port

  postgres-db-dev:
    image: postgis/postgis:14-master
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

# ----------Network------------
networks:
  default:
    name: safe_cities
# ---------Volumes-------------
volumes:
  postgres-data-dev:
